name: example
recipe: drupal8
config:
  webroot: .
  drush: "*"
  php: '7.3'
  database: mysql:5.7.27
  framework: drupal
  env: dev
proxy:
  appserver:
    - local.example.com
tooling:
  drush:
    cmd: /usr/local/bin/drush
  abracadabra:
    service: appserver
    description: Install Drupal per my requirements.
    cmd:
      - composer install
      - drush si minimal --db-url=mysql://drupal8:drupal8@database.example.internal:3306/drupal8 --site-name=example-automated -y
      - drush cset system.site uuid MY_CUSTOM_UUID_HERE -y
      - drush config-import sync -y
      - drush locale-check
      - drush locale-update
      - drush updatedb -y
      - drush cr
  dejavu:
    service: appserver
    description: Import and apply new config changes (the same automated action that happend before).
    cmd:
      - composer install
      - drush config-import sync -y
      - drush locale-check
      - drush locale-update
      - drush updatedb -y
      - drush cr
  locale:
    service: appserver
    description: Check and update locale and do cache rebuild.
    cmd:
      - drush locale-check
      - drush locale-update
      - drush cr
services:
  appserver:
    xdebug: true
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
  mymailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
